// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBATZqqvydd3tdbZqFQn2E0tFIzY_aRZV4',
    appId: '1:251165701603:web:093583934afeeaadf6dcd6',
    messagingSenderId: '251165701603',
    projectId: 'portal-alumni-120f7',
    authDomain: 'portal-alumni-120f7.firebaseapp.com',
    storageBucket: 'portal-alumni-120f7.firebasestorage.app',
    measurementId: 'G-VCFQBBQT10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzCjh6ffvnUl0tGNeVTs2YMpD7e_9fxjE',
    appId: '1:251165701603:android:8dd120b0801e3103f6dcd6',
    messagingSenderId: '251165701603',
    projectId: 'portal-alumni-120f7',
    storageBucket: 'portal-alumni-120f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2vRxGuiewFaqWOEUBwPV33OjJ5QB1MRo',
    appId: '1:251165701603:ios:db848cde9b77ffc1f6dcd6',
    messagingSenderId: '251165701603',
    projectId: 'portal-alumni-120f7',
    storageBucket: 'portal-alumni-120f7.firebasestorage.app',
    iosBundleId: 'com.example.alumniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2vRxGuiewFaqWOEUBwPV33OjJ5QB1MRo',
    appId: '1:251165701603:ios:db848cde9b77ffc1f6dcd6',
    messagingSenderId: '251165701603',
    projectId: 'portal-alumni-120f7',
    storageBucket: 'portal-alumni-120f7.firebasestorage.app',
    iosBundleId: 'com.example.alumniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBATZqqvydd3tdbZqFQn2E0tFIzY_aRZV4',
    appId: '1:251165701603:web:7115d0139fcdd13df6dcd6',
    messagingSenderId: '251165701603',
    projectId: 'portal-alumni-120f7',
    authDomain: 'portal-alumni-120f7.firebaseapp.com',
    storageBucket: 'portal-alumni-120f7.firebasestorage.app',
    measurementId: 'G-SWWNRCGT7D',
  );
}
